version: 2
project_name: rke2diff
release:
  github:
    owner: mikejoh
    name: rke2diff
  name_template: 'v{{ .Tag }}'
builds:
  - id: rke2diff
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - windows_amd64_v1
    dir: .
    main: ./cmd/rke2diff/
    binary: rke2diff
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -s -w -X=github.com/mikejoh/rke2diff/internal/buildinfo.Version={{ .Version }} -X=github.com/mikejoh/rke2diff/internal/buildinfo.Name=rke2diff -X=github.com/mikejoh/rke2diff/internal/buildinfo.GitSHA={{ .Commit }}
dist: ./build
